Florian sandbox
project-ida/nuclear pull request #4
Opened 2020-11-30 16:51 UTC by fwmetzler

I created a new notebook which depicts different parts of the internuclear potential. 

Potential issues with the preview may arise due to the import and use of a dygraph library via files in the dygraphs subfolder. Let's maybe try out and see whether nbviewer and/or Colab can handle this or not.

2020-12-01 13:13 UTC, mklilley requested changes
Lovely to see this all in a nicely presented notebook. Just a few changes will make it ready I'd say.

2020-12-01 13:13 UTC, mklilley commented on src/01-nuclear-energetics.md
> +#plt.xlim(50,100);
Looks like you modified nuclear energetics file - did you mean to do this?

2020-12-01 13:13 UTC, mklilley commented on src/02-internuclear-potentials.md
> +This notebooks looks at different sections of the internuclear potential between two nuclei, specifically two deuterium nuclei as in the case of a molecule of deuterons D2.
Typo - this notebook

2020-12-01 13:13 UTC, mklilley commented on src/02-internuclear-potentials.md
> +    # I had to add +1 to the minimum energy and adjust a accordingly
Why did you need to do this?

2020-12-01 13:13 UTC, mklilley commented on src/02-internuclear-potentials.md
> +plt.show()
Would be nice to have a legend

2020-12-01 13:13 UTC, mklilley commented on src/02-internuclear-potentials.md
> +plt.show()
Would be nice to have a legend

2020-12-01 13:13 UTC, mklilley commented on src/02-internuclear-potentials.md
> +plt.show()
Would be nice to have a legend

2020-12-01 13:13 UTC, mklilley commented on src/02-internuclear-potentials.md
> +V0 = 28.5e6 #50 # ground state energy see for He-4 https://pdfs.semanticscholar.org/4c24/b2d33f3b3ca2f288897967dc3a6fdb51f1a0.pdf
What does the number 50 mean?

2020-12-01 13:13 UTC, mklilley commented on src/02-internuclear-potentials.md
> +The Woods-Saxon (WS) potential is a mean potential that is assumed to reasonably describe the attraction of the nuclear force from a given nucleus with A=number of nucleons.
Would be nice to have a Latex formula like you had for the Morse potential

2020-12-01 13:13 UTC, mklilley commented on src/02-internuclear-potentials.md
> +thisr
`thisr ` - I think you can delete that

2020-12-01 13:13 UTC, mklilley commented on src/02-internuclear-potentials.md
> +thisws
`thisws` - I think you can remove this

2020-12-01 13:13 UTC, mklilley commented on src/02-internuclear-potentials.md
> +plt.xlim(0,0.01)
Why is there a discontinuity in the graph?

2020-12-01 13:13 UTC, mklilley commented on src/02-internuclear-potentials.md
> +fig.show()
Cannot see the graph

2020-12-01 13:23 UTC, mklilley commented on src/02-internuclear-potentials.md
> +<a href="https://colab.research.google.com/github/project-ida/nuclear/blob/master/02-internuclear-potentials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg
`nuclear/blob` should be `nuclear-reactions/blob`

2020-12-05 19:58 UTC, fwmetzler commented on src/02-internuclear-potentials.md
> +    # I had to add +1 to the minimum energy and adjust a accordingly
I'm not sure what determines the absolute values of the floating potentials. I added some more comments and for now I'll just say that I had to do it to match the KW potential to the formula given in KN

2020-12-05 19:58 UTC, fwmetzler commented on src/01-nuclear-energetics.md
> +#plt.xlim(50,100);
Thanks for pointing this out. I didn't meant to do this.

2020-12-05 20:06 UTC, fwmetzler commented on src/02-internuclear-potentials.md
> +plt.show()
Added it for the next iteration

2020-12-05 20:08 UTC, fwmetzler commented on src/02-internuclear-potentials.md
> +plt.show()
Added it for the next iteration

2020-12-05 20:19 UTC, fwmetzler commented on src/02-internuclear-potentials.md
> +The Woods-Saxon (WS) potential is a mean potential that is assumed to reasonably describe the attraction of the nuclear force from a given nucleus with A=number of nucleons.
Yes, great point. I added that and a bit more explanation

2020-12-05 20:19 UTC, fwmetzler commented on src/02-internuclear-potentials.md
> +thisr
done

2020-12-05 20:19 UTC, fwmetzler commented on src/02-internuclear-potentials.md
> +thisws
done

2020-12-05 20:45 UTC, fwmetzler commented
I implemented the suggested changes and will start a new pull request

2020-12-05 20:45 UTC, closed without merging